### ISSUE TITLE
Research how to implement software for flow meters

### ISSUE THREAD

**Issue by amavalankar** [InspirationRobotics/inspiration_robosub#47]
Given that we will be using flow sensors to determine velocity and position, we have to determine:

- [ ] How will this interface with the software stack
- [ ] In what configuration will we have these sensors?
- [ ] How will we integrate the raw data given by the sensors into a program?
- [ ] How can we test the sensor(s)?

**Comment by ashiriag** [comment]
@amavalankar @rveerepalli Please see if you agree with this diagram: https://app.diagrams.net/#G1o7Ohcx3cmxKpuGvy0YqnEsLZtuzRkS-7
