### ISSUE TITLE
Integrate traditional CV with old Orange repo

### ISSUE THREAD

**Issue by amavalankar** [InspirationRobotics/inspiration_robosub#61]
- [x] Create and implement navigation data communicator
- [ ] Have CV provide data to the navigation data communicator
- [ ] Implement cv data to make program that can run on Orange (using old repo, of course!)
- [ ] Test on Orange in the pool (exciting! XD)

**Comment by ashiriag** [comment]
@pahels 
[Here](https://docs.google.com/document/d/1FwL1aaRDlq-XRCicFf3A6KHnoXQZ79fdhmcaOLCeZt8/edit) is the document where Raina and I recorded our testing on the BlueROV. 

The current issue is that when there is a stable environment in front of the camera, the coordinates are unreasonable or fluctuating a lot. To be able to use this, navigation would need to either receive no values if nothing is detected or receive a confidence level on the coordinates.
